import Cover from './components/Cover'
import Navbar from './components/Navbar'
import Works from './components/Works'

function App() {
  
  return (
    <>
      <Navbar/>
      <Cover/>
      <Works/>
      <div>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</div>
      <div>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</div>
      <div>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</div>
      <div>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</div>
      <div>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</div>
      <div>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</div>
      <div>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</div>
      <div>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</div>
      <div>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</div>
      <div>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</div>
      <div>HELOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO</div>
    </>
  )
}

export default App
